export const Images = {
    LeftArrow: require('../Assets/Image/left.png'),
    RightArrow: require('../Assets/Image/right.png'),
    User: require('../Assets/Image/user.png'),
    GoogleMap: require('../Assets/Image/placeholder.png'),
    Calculator: require('../Assets/Image/calculator.png'),
    VideoPlay: require('../Assets/Image/player.png'),
    Calander: require('../Assets/Image/calendar.png'),
    Apple: require('../Assets/Image/Apple.png'),
    Google: require('../Assets/Image/google_icon.png'),
    Facebook: require('../Assets/Image/facebook_icon.png'),
    Email: require('../Assets/Image/Email.jpg'),
    Password: require('../Assets/Image/Pass.jpg'),
    Play: require('../Assets/Image/play.png'),
    BackArroe: require('../Assets/Image/BackArrow.png'),
    Drawericon: require('../Assets/Image/drawer2.png'),
    DrawerIcon1: require('../Assets/Image/Grouphhhhh.png'),
    ///// images
    Profile: require('../Assets/Image/profile.jpeg'),
    Name: require('../Assets/Image/Name.jpg'),
    Address: require('../Assets/Image/Add.jpg'),
    Contact: require('../Assets/Image/Contacts.jpg'),
    ProfileOpt: require('../Assets/Image/profile.png'),
    SearchIcon: require('../Assets/Image/Search.png'),
    Photo:require('../Assets/Image/image.png'),
}